# Generated by Django 6.0.6 on 2026-07-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IslamicMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('event_key', models.CharField(choices=[('MUHARRAM', '1st of Muharram (Islamic New Year)'), ('RAMADAN', '1st of Ramadan (Month of Fasting)'), ('EID_FITR', 'Eid al-Fitr (1st of Shawwal)'), ('EID_ADHA', 'Eid al-Adha (10th of Dhul Hijjah)'), ('MILAD', 'Milad un-Nabi (12th of Rabi al-Awwal)')], max_length=20)),
                ('expected_gregorian_date', models.DateField()),
                ('moon_age_at_sunset', models.FloatField(help_text='Age in hours since conjunction')),
                ('illumination_percentage', models.FloatField(help_text='Percentage illuminated')),
                ('lag_time_minutes', models.FloatField(help_text='Minutes between sunset and moonset')),
                ('is_visible_in_delhi', models.BooleanField(default=False)),
                ('visibility_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
    ]
